remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Econ CMU Next-Gen Work]
description:
  [
    การพลิกโฉมการทำงานในคณะเศรษฐศาสตร์ด้วย AppSheet,
    Google Apps Script และ Data Studio: การออกแบบ พัฒนา และประยุกต์ใช้งานเพื่อเพิ่มประสิทธิภาพองค์กร,
  ]
